### PR TITLE
Updating vulnerable and outdated dependencies

### PR DESCRIPTION
**Pull request by lirantal**
Please refer to the following dependencies reports:
1. Vulnerabilities discovered by snyk: https://snyk.io/test/github/codefresh-io/cf-logs
2. Outdated dev dependencies by bithound: https://www.bithound.io/github/codefresh-io/cf-logs/develop/files

A follow-up PR that could help here is to integrate Snyk with the GitHub repository or scan it through a travis automated build.

### CODE REVIEW

**Comment by lirantal** [comment]
Closing due to lack of interest.

**Comment by advance512** [comment]
Was this an automated PR?

**Comment by lirantal** [comment]
No, why automated? I opened it from genuine concern when reviewing the project :-)

**Comment by menalon** [comment]
why we didn't approved the PR ?

**Comment by lirantal** [comment]
You're asking me? I don't know :)
Maybe you missed it.

**Pull request closed without merging**
